// Lightweight, shared "a report was started" registry — the missing piece
// that let API-only report generation (curl, Postman, another service —
// anything that isn't the frontend's own browser session) disappear from
// Report History entirely. Report History previously lived only in the
// browser's localStorage, written by each module's page component after
// receiving the SSE 'result' event; a report generated by hitting the API
// directly never passed through that code, so it was invisible.
//
// This registry doesn't replace localStorage-based history — it's what lets
// GET /api/reports/recent (see routes/reports.ts) tell the frontend "here
// are jobIds that exist server-side, some of which you may not have in your
// local history yet." Each module's POST route registers a job the moment
// it's created; the aggregator route then looks up each one's current
// status via that module's own getXxxJob getter.
//
// In-memory, capped, same lifetime tradeoff as every job store and the
// usage logs in this app — resets on redeploy.

export interface RegisteredReport {
  moduleType: string;
  jobId: string;
  label: string; // best-effort human-readable identifier (company name, industry, etc.)
  createdAt: string;
}

const MAX_ENTRIES = 500;
const registry: RegisteredReport[] = [];

export function registerJobStart(moduleType: string, jobId: string, label: string): void {
  registry.push({ moduleType, jobId, label, createdAt: new Date().toISOString() });
  if (registry.length > MAX_ENTRIES) registry.shift();
}

export function getRegisteredReports(): RegisteredReport[] {
  return registry;
}

// Best-effort label extraction from a POST body — field names vary by
// module, so this checks the common ones in priority order rather than
// requiring each route to compute its own label.
export function extractLabel(body: Record<string, unknown>): string {
  const candidates = [
    'companyName', 'targetCompany', 'userFirm', 'industryOrSegment', 'industry',
    'userOrganization', 'topic', 'query', 'jobTitle',
  ];
  for (const key of candidates) {
    const v = body[key];
    if (typeof v === 'string' && v.trim()) return v.trim();
  }
  if (Array.isArray(body.postings) && body.postings.length > 0) {
    const first = body.postings[0] as Record<string, unknown>;
    if (typeof first?.jobTitle === 'string') return `${body.postings.length} job posting(s)`;
  }
  return 'Untitled';
}
